### ISSUE TITLE
License file?

### ISSUE THREAD

**Issue by h5rdly** [dacez/zzzjson#2]
Hi,

This looks great, but I'm not sure if/how am I allowed to use zzzjson.

Could you perhaps add a license?

Thanks,
Eli

**Comment by h5rdly** [comment]
Hi,

This looks great, but I'm not sure if/how am I allowed to use zzzjson. 

Could you perhaps add a license?


Thanks,
Eli

**Comment by dacez** [comment]
https://github.com/dacez/zzzjson/blob/master/LICENSE

**Comment by h5rdly** [comment]
Best license I've read

**Comment by Himujjal** [comment]
Please keep the license as it is. You have done an incredible job with zzzjson. Its sad to see so many less Github stars.
