### ISSUE TITLE
[Not an issue] Can I know what algorithm is being used here?

### ISSUE THREAD

**Issue by Himujjal** [dacez/zzzjson#3]
I didn't really understand how you parsed the unicode in the following line of code:
[zj_consumeStr](https://github.com/dacez/zzzjson/blob/e9cf1f7e4e5c50bddc54300c79e2c33ba433fe16/zzzjson.h#L1149) function.

Can you please explain this part? What are the magic numbers; `0xDC00`, `0xDFFF`, `0xD800``0xDBFF` that are being used here and why these checks?

I am using this library as a reference to build a lexer for another parser. Help would be appreciated

**Comment by dacez** [comment]
Unicode range D800–DFFF is used for surrogate pairs in UTF-16 (used by Windows) and CESU-8 transformation formats, allowing these encodings to represent the
supplementary plane code points, whose values are too large to fit in 16 bits. A pair of 16-bit code points — the first from the high surrogate area (D800–DBFF),
and the second from the low surrogate area (DC00–DFFF) — are combined to form a 32-bit code point from the supplementary planes.
Unicode and ISO/IEC 10646 do not assign actual characters to any of the code points in the D800–DFFF range — these code points only have meaning when used
in surrogate pairs. Hence an individual code point from a surrogate pair does not represent a character, is invalid unless used in a surrogate pair, and is
unconditionally invalid in UTF-32 and UTF-8 (if strict conformance to the standard is applied).


https://en.wikibooks.org/wiki/Unicode/Character_reference/D000-DFFF

**Comment by Himujjal** [comment]
Thanks a lot for this info. I learnt a lot about Unicode!
